package com.sih.cognicare.service;

import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Base64;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

/**
 * Lightweight HS256 JWT generator (demo grade — no external dependency).
 * Emits a well-formed {@code header.payload.signature} token so the auth
 * contract can be swapped for a full jjwt/spring-security setup later.
 */
@Service
public class JwtService {

    private static final String ALGORITHM = "HmacSHA256";
    private static final String SECRET = "cognicare-kiosk-secret-key-change-me";
    private static final long TOKEN_TTL_SECONDS = 12 * 60 * 60;

    public String generateToken(Long subject) {
        long nowSeconds = System.currentTimeMillis() / 1000;
        long expSeconds = nowSeconds + TOKEN_TTL_SECONDS;

        String headerJson = "{\"alg\":\"HS256\",\"typ\":\"JWT\"}";
        String payloadJson = "{\"sub\":\"" + subject + "\",\"iat\":" + nowSeconds
                + ",\"exp\":" + expSeconds + "}";

        String encodedHeader = base64Url(headerJson);
        String encodedPayload = base64Url(payloadJson);
        String signingInput = encodedHeader + "." + encodedPayload;
        String signature = base64Url(hmacSha256(signingInput));

        return signingInput + "." + signature;
    }

    private String base64Url(String value) {
        return Base64.getUrlEncoder().withoutPadding()
                .encodeToString(value.getBytes(StandardCharsets.UTF_8));
    }

    private String base64Url(byte[] value) {
        return Base64.getUrlEncoder().withoutPadding().encodeToString(value);
    }

    private byte[] hmacSha256(String data) {
        try {
            Mac mac = Mac.getInstance(ALGORITHM);
            SecretKeySpec keySpec = new SecretKeySpec(
                    SECRET.getBytes(StandardCharsets.UTF_8), ALGORITHM);
            mac.init(keySpec);
            return mac.doFinal(data.getBytes(StandardCharsets.UTF_8));
        } catch (Exception e) {
            throw new IllegalStateException("Could not sign JWT", e);
        }
    }

    /**
     * Validates the signature and {@code exp} claim of a token generated by
     * this service. Returns {@code true} only for well-formed, correctly
     * signed, and not-yet-expired tokens.
     */
    public boolean isValid(String token) {
        try {
            String[] parts = token.split("\\.");
            if (parts.length != 3) {
                return false;
            }
            String expected = base64Url(hmacSha256(parts[0] + "." + parts[1]));
            if (!MessageDigest.isEqual(
                    expected.getBytes(StandardCharsets.UTF_8),
                    parts[2].getBytes(StandardCharsets.UTF_8))) {
                return false;
            }
            long nowSeconds = System.currentTimeMillis() / 1000;
            return extractExp(parts[1]) > nowSeconds;
        } catch (Exception e) {
            return false;
        }
    }

    private long extractExp(String payload) {
        try {
            Base64.Decoder decoder = Base64.getUrlDecoder();
            byte[] bytes = decoder.decode(payload);
            String json = new String(bytes, StandardCharsets.UTF_8);
            String marker = "\"exp\":";
            int index = json.indexOf(marker);
            if (index < 0) {
                return 0;
            }
            int start = index + marker.length();
            int end = start;
            while (end < json.length() && Character.isDigit(json.charAt(end))) {
                end++;
            }
            if (end == start) {
                return 0;
            }
            return Long.parseLong(json.substring(start, end));
        } catch (Exception e) {
            return 0;
        }
    }
}